<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('products')->truncate();

        DB::table('products')->insert([

            [
                'id' => 1,
                'name' => 'Playera',
                'description' => 'Batman La Serie Animada',
                'price' => 200.00,
                'sizes' => json_encode(["L","XL","S","M"]),
                'colors' => json_encode(["Negro"]),
                'images' => json_encode(["products/irqfA9eQOTcogF1nNtUFYZYjFArmObdeGxzaDsJO.png"]),
                'stock' => 1,
                'stock_por_talla' => json_encode([
                    "L" => 1,
                    "XL" => 1,
                    "S" => 1,
                    "M" => 1
                ]),
                'is_active' => true,
                'categoria' => null,
                'expires_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 2,
                'name' => 'Playera Mamá',
                'description' => 'Playera de Mamá con Mario Bros',
                'price' => 200.00,
                'sizes' => json_encode(["S","M","L","XL","XXL"]),
                'colors' => json_encode(["Negro"]),
                'images' => json_encode(["products/BBVtgf6CSjSNk4qXl8WdM1YeIU7hg1UMaRyZEjTI.png"]),
                'stock' => 1,
                'stock_por_talla' => json_encode([]),
                'is_active' => true,
                'categoria' => 'Día de las madres',
                'expires_at' => '2026-05-15 07:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 3,
                'name' => 'Playera Mamá',
                'description' => 'La mamá mas bonita',
                'price' => 200.00,
                'sizes' => json_encode(["M","L","XL","S"]),
                'colors' => json_encode(["Negro"]),
                'images' => json_encode(["products/aq2MAHotxFzJfwA8iusRjTyu6NN5NoF4gWgPZALa.png"]),
                'stock' => 1,
                'stock_por_talla' => json_encode([
                    "S" => 0,
                    "M" => 0,
                    "L" => 0,
                    "XL" => 0
                ]),
                'is_active' => true,
                'categoria' => 'Día de las madres',
                'expires_at' => '2026-05-15 07:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 4,
                'name' => 'Playera Street Fighter',
                'description' => null,
                'price' => 200.00,
                'sizes' => json_encode(["S","M","L","XL"]),
                'colors' => json_encode(["Negro"]),
                'images' => json_encode(["products/WvOmDaMkkqr6PZgwhhhyrI5fju2GlNkSac0hcJ8F.png"]),
                'stock' => 1,
                'stock_por_talla' => json_encode([]),
                'is_active' => true,
                'categoria' => null,
                'expires_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 5,
                'name' => 'Playera de Mortal Kombat',
                'description' => null,
                'price' => 200.00,
                'sizes' => json_encode(["S","M","L","XL"]),
                'colors' => json_encode(["Negro"]),
                'images' => json_encode(["products/vUJd9h9Nkio5UcjUUKgZgkFppuVxeoS7Kozc7K0T.png"]),
                'stock' => 1,
                'stock_por_talla' => json_encode([]),
                'is_active' => true,
                'categoria' => null,
                'expires_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 6,
                'name' => 'Playera Mortal Kombat',
                'description' => null,
                'price' => 200.00,
                'sizes' => json_encode(["S","M","L","XL"]),
                'colors' => json_encode(["Negro"]),
                'images' => json_encode(["products/iZ8JxjUxNgq1pkVd6SvrR58SlspfbNhPNsScILz1.png"]),
                'stock' => 1,
                'stock_por_talla' => json_encode([]),
                'is_active' => true,
                'categoria' => null,
                'expires_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 7,
                'name' => 'Playera SuitZero',
                'description' => null,
                'price' => 200.00,
                'sizes' => json_encode(["S","M","XL","L"]),
                'colors' => json_encode(["Negro"]),
                'images' => json_encode(["products/28Z8i7j4S77ERPIyO5cHVSM6duduCoi1eZOpdD3S.png"]),
                'stock' => 1,
                'stock_por_talla' => json_encode([]),
                'is_active' => true,
                'categoria' => null,
                'expires_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 8,
                'name' => 'Playera SuperMamá',
                'description' => 'Playera para una Super mamá',
                'price' => 200.00,
                'sizes' => json_encode(["S","M","L","XL"]),
                'colors' => json_encode(["Negro"]),
                'images' => json_encode(["products/8dhqd9dvnwpJFacEQefs7sk2LBSw06MEHWJpVRxX.png"]),
                'stock' => 1,
                'stock_por_talla' => json_encode([]),
                'is_active' => true,
                'categoria' => 'Día de las madres',
                'expires_at' => '2026-05-15 07:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 9,
                'name' => 'Playera para mamá',
                'description' => 'Playera "Existe una mujer perfecta..."',
                'price' => 200.00,
                'sizes' => json_encode(["S","M","L","XL"]),
                'colors' => json_encode(["Negro"]),
                'images' => json_encode(["products/Om4AOD8ZzE28fzuYB6ShCjGfhT6ak4ZDc3pWshFx.png"]),
                'stock' => 1,
                'stock_por_talla' => json_encode([]),
                'is_active' => true,
                'categoria' => 'Día de las madres',
                'expires_at' => '2026-05-15 07:00:00',
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 10,
                'name' => 'Playera Mundial',
                'description' => 'Copa 2026',
                'price' => 200.00,
                'sizes' => json_encode(["S","M","L","XL"]),
                'colors' => json_encode(["Negro"]),
                'images' => json_encode(["products/3thhdyj0J1dgeuElkZolyHPJpzczFEILWE8nZycf.png"]),
                'stock' => 1,
                'stock_por_talla' => json_encode([]),
                'is_active' => true,
                'categoria' => null,
                'expires_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 11,
                'name' => 'Playera FIFA',
                'description' => 'Copa FIFA 2026',
                'price' => 200.00,
                'sizes' => json_encode(["S","M","L","XL"]),
                'colors' => json_encode(["Negro"]),
                'images' => json_encode(["products/KOPxnqIgTRsSj4J4VsmPi2FbRwT2m2Y9AhIXeY5G.png"]),
                'stock' => 1,
                'stock_por_talla' => json_encode([]),
                'is_active' => true,
                'categoria' => null,
                'expires_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 12,
                'name' => 'Playera del Mundial',
                'description' => 'FIFA World Cup',
                'price' => 200.00,
                'sizes' => json_encode(["S","M","L","XL"]),
                'colors' => json_encode(["Negro"]),
                'images' => json_encode(["products/JHJ0uigSfInhyYGuwqo26fZPHVPn2nnZoC59ML70.png"]),
                'stock' => 1,
                'stock_por_talla' => json_encode([]),
                'is_active' => true,
                'categoria' => null,
                'expires_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 13,
                'name' => 'Playera Mundial 2026',
                'description' => null,
                'price' => 200.00,
                'sizes' => json_encode(["S","M","L","XL"]),
                'colors' => json_encode(["Negro"]),
                'images' => json_encode(["products/wach1o3kkIuz1xBdbuv4omURNbPDoYNZQOjJPXqO.png"]),
                'stock' => 1,
                'stock_por_talla' => json_encode([]),
                'is_active' => true,
                'categoria' => null,
                'expires_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

            [
                'id' => 14,
                'name' => 'Playera 2026',
                'description' => 'Canadá, México, USA',
                'price' => 200.00,
                'sizes' => json_encode(["S","M","L","XL"]),
                'colors' => json_encode(["Negro"]),
                'images' => json_encode(["products/10wIeoYreVDExV3AFINLG3Qw20GE6EiomkNqHBZR.png"]),
                'stock' => 1,
                'stock_por_talla' => json_encode([]),
                'is_active' => true,
                'categoria' => null,
                'expires_at' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],

        ]);
    }
}